# Generated by Django 5.2.8 on 2025-11-09 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthEstablishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "Hôpital"),
                            ("CLINIC", "Clinique"),
                            ("DISPENSARY", "Dispensaire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("region", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("UPDATE", "Modification"),
                            ("DELETE", "Suppression"),
                            ("LOGIN", "Connexion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=100)),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accueil_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VACCINE", "Rappel vaccin"),
                            ("CAMPAIGN", "Campagne santé"),
                            ("WEATHER", "Alerte météo"),
                            ("EPIDEMIC", "Alerte épidémie"),
                            ("NEWS", "Actualité santé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title_fr", models.CharField(max_length=200)),
                ("title_ful", models.CharField(max_length=200)),
                ("message_fr", models.TextField()),
                ("message_ful", models.TextField()),
                ("related_url", models.URLField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accueil_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vaccine_reminders", models.BooleanField(default=True)),
                ("campaign_alerts", models.BooleanField(default=True)),
                ("weather_alerts", models.BooleanField(default=True)),
                ("epidemic_alerts", models.BooleanField(default=True)),
                ("news_notifications", models.BooleanField(default=True)),
                ("quiet_hours_start", models.TimeField(default="22:00")),
                ("quiet_hours_end", models.TimeField(default="07:00")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accueil_notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "Français"), ("ful", "Fulfulde")],
                        default="fr",
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("0-4", "0–4 ans"),
                            ("5-14", "5–14 ans"),
                            ("15-24", "15–24 ans"),
                            ("25-44", "25–44 ans"),
                            ("45-64", "45–64 ans"),
                            ("65+", "65 ans et plus"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Homme"),
                            ("F", "Femme"),
                            ("O", "Autre"),
                            ("N", "Préfère pas dire"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "is_pregnant",
                    models.CharField(
                        choices=[
                            ("yes", "Oui"),
                            ("no", "Non"),
                            ("na", "Ne s'applique pas"),
                        ],
                        default="na",
                        max_length=3,
                    ),
                ),
                ("region", models.CharField(max_length=100)),
                ("village", models.CharField(blank=True, max_length=100)),
                ("data_consent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
