# Generated by Django 5.2.8 on 2025-11-10 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accueil", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "Hôpital"),
                            ("CLINIC", "Clinique"),
                            ("PHARMACY", "Pharmacie"),
                            ("DISPENSARY", "Dispensaire"),
                            ("HEALTH_CENTER", "Centre de santé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("region", models.CharField(max_length=100)),
                ("village", models.CharField(max_length=100)),
                ("latitude", models.FloatField(help_text="Coordonnée GPS - latitude")),
                (
                    "longitude",
                    models.FloatField(help_text="Coordonnée GPS - longitude"),
                ),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                (
                    "available_medications",
                    models.JSONField(
                        default=list,
                        help_text="Liste des médicaments disponibles (noms ou IDs)",
                    ),
                ),
                (
                    "operating_hours",
                    models.CharField(default="08:00-18:00", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Centre de santé",
                "verbose_name_plural": "Centres de santé",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom commercial du médicament", max_length=200
                    ),
                ),
                (
                    "generic_name",
                    models.CharField(help_text="Nom générique", max_length=200),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ANTIMALARIAL", "Antipaludique"),
                            ("ANTIBIOTIC", "Antibiotique"),
                            ("ANALGESIC", "Antidouleur"),
                            ("ANTIPYRETIC", "Antifièvre"),
                            ("ANTIHISTAMINE", "Antihistaminique"),
                            ("VITAMIN", "Vitamine"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prescription_required", models.BooleanField(default=False)),
                ("common_uses", models.TextField(help_text="Indications courantes")),
                (
                    "dosage_forms",
                    models.JSONField(
                        default=list,
                        help_text="Formes disponibles (comprimés, sirop, etc.)",
                    ),
                ),
                (
                    "side_effects",
                    models.TextField(
                        blank=True, help_text="Effets secondaires courants"
                    ),
                ),
                (
                    "contraindications",
                    models.TextField(blank=True, help_text="Contre-indications"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Médicament",
                "verbose_name_plural": "Médicaments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_ful", models.CharField(blank=True, max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FEVER", "Fièvre"),
                            ("PAIN", "Douleur"),
                            ("RESPIRATORY", "Respiratoire"),
                            ("DIGESTIVE", "Digestif"),
                            ("SKIN", "Peau"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyen"),
                            ("HIGH", "Élevé"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Symptôme",
                "verbose_name_plural": "Symptômes",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="adminauditlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Log d'audit",
                "verbose_name_plural": "Logs d'audit",
            },
        ),
        migrations.AlterModelOptions(
            name="healthestablishment",
            options={
                "ordering": ["name"],
                "verbose_name": "Établissement de santé",
                "verbose_name_plural": "Établissements de santé",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationsettings",
            options={
                "verbose_name": "Paramètre de notification",
                "verbose_name_plural": "Paramètres de notification",
            },
        ),
        migrations.AddField(
            model_name="adminauditlog",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="healthestablishment",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="healthestablishment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="healthestablishment",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="scheduled_for",
            field=models.DateTimeField(
                blank=True, help_text="Planification de l'envoi", null=True
            ),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="language_preference",
            field=models.CharField(
                choices=[("fr", "Français"), ("ful", "Fulfulde")],
                default="fr",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="medication_reminders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="allergies_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="allow_geolocation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="audio_preference",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="chronic_diseases",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gsm_access",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="has_allergies",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="health_access",
            field=models.CharField(
                choices=[
                    ("good", "Bon accès"),
                    ("limited", "Accès limité"),
                    ("poor", "Mauvais accès"),
                    ("unknown", "Inconnu"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="internet_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="medication_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="no_mosquito_net",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="other_disease",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="outdoor_work",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profession",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="recent_symptoms",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="regular_medication",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="stagnant_water",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="vaccination_status",
            field=models.CharField(
                choices=[
                    ("up_to_date", "À jour"),
                    ("partial", "Partiel"),
                    ("none", "Aucun"),
                    ("unknown", "Inconnu"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="adminauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Création"),
                    ("UPDATE", "Modification"),
                    ("DELETE", "Suppression"),
                    ("LOGIN", "Connexion"),
                    ("EXPORT", "Export"),
                    ("BACKUP", "Sauvegarde"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="healthestablishment",
            name="type",
            field=models.CharField(
                choices=[
                    ("HOSPITAL", "Hôpital"),
                    ("CLINIC", "Clinique"),
                    ("DISPENSARY", "Dispensaire"),
                    ("LABORATORY", "Laboratoire"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("VACCINE", "Rappel vaccin"),
                    ("CAMPAIGN", "Campagne santé"),
                    ("WEATHER", "Alerte météo"),
                    ("EPIDEMIC", "Alerte épidémie"),
                    ("NEWS", "Actualité santé"),
                    ("MEDICATION", "Rappel médicament"),
                    ("APPOINTMENT", "Rappel rendez-vous"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DiagnosisRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition_fr", models.CharField(max_length=200)),
                ("condition_ful", models.CharField(max_length=200)),
                ("recommendation_fr", models.TextField()),
                ("recommendation_ful", models.TextField()),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Peu urgent"),
                            ("MEDIUM", "Urgent"),
                            ("HIGH", "Très urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_medications",
                    models.ManyToManyField(blank=True, to="accueil.medication"),
                ),
                (
                    "symptoms",
                    models.ManyToManyField(
                        related_name="diagnoses", to="accueil.symptom"
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommandation de diagnostic",
                "verbose_name_plural": "Recommandations de diagnostic",
                "ordering": ["condition_fr"],
            },
        ),
        migrations.CreateModel(
            name="VoiceQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fulfulde_audio",
                    models.FileField(blank=True, null=True, upload_to="voice_queries/"),
                ),
                (
                    "fulfulde_text",
                    models.TextField(
                        help_text="Transcription Fulfulde de la requête vocale"
                    ),
                ),
                (
                    "french_translation",
                    models.TextField(help_text="Traduction française de la requête"),
                ),
                (
                    "chatbot_response_fr",
                    models.TextField(help_text="Réponse du chatbot en français"),
                ),
                (
                    "chatbot_response_ful",
                    models.TextField(help_text="Réponse traduite en Fulfulde"),
                ),
                (
                    "health_centers",
                    models.JSONField(
                        default=list, help_text="Centres de santé à proximité"
                    ),
                ),
                (
                    "medications",
                    models.JSONField(default=list, help_text="Médicaments recommandés"),
                ),
                ("user_latitude", models.FloatField(blank=True, null=True)),
                ("user_longitude", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Requête vocale",
                "verbose_name_plural": "Requêtes vocales",
                "ordering": ["-created_at"],
            },
        ),
    ]
