# Generated by Django 5.2.8 on 2025-11-09 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VACCINE", "Rappel vaccin"),
                            ("CAMPAIGN", "Campagne santé"),
                            ("WEATHER", "Alerte météo"),
                            ("EPIDEMIC", "Alerte épidémie"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title_fulfulde", models.CharField(max_length=200)),
                ("message_fulfulde", models.TextField()),
                ("related_url", models.URLField(blank=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vaccine_reminders", models.BooleanField(default=True)),
                ("campaign_alerts", models.BooleanField(default=True)),
                ("weather_alerts", models.BooleanField(default=True)),
                ("epidemic_alerts", models.BooleanField(default=True)),
                ("quiet_hours_start", models.TimeField(default="22:00")),
                ("quiet_hours_end", models.TimeField(default="07:00")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
